// The 3DS environment-light record, as both games store it. GAME-AGNOSTIC.
//
// Why this is shared and the LAYOUT is not: the record's tail is a byte-for-byte copy of the N64
// `EnvLightSettings` (2ship/include/z64environment.h for MM, and the same struct in SoH), and the
// six colour triples keep the N64's internal spacing under a single uniform shift. So the TYPE is one
// type for both games, while the OFFSETS are per-game and are recovered per-game:
//
//   OoT3D:  f32 zFar, f32 fogFar, u16 fogNear|blendRate<<10, pad, N64 block at +0x0A, stride 0x1C
//   MM3D:   f32 zFar, f32 fogFar, u16 fogNear|blendRate<<10, pad, N64 block at +0x0B, stride 0x20
//
// MM3D's block is ONE BYTE past OoT3D's. That is the whole hazard: a consumer that hard-codes one
// game's offsets and is handed the other's data reads MM3D's `fogColor` as its second light colour
// -- a wrong value with exactly the right shape, so nothing looks broken. The per-game tables
// (`Shipwright/soh/src/zelda3d/tables/zelda3d_scene_lighting.inc` and
// `2ship/2s2h/zelda3d/mm3d_scene_lighting.inc`) are generated by their own tools and are gated
// two-sided against the other game's data, so the offsets cannot be quietly swapped.
//
// Generated tables include this header's types; nothing here has behaviour, no globals, and no
// dependency on either game's own headers.
#ifndef ZELDA3D_SHARED_LIGHTING_ZELDA3D_ENV_RECORD_H
#define ZELDA3D_SHARED_LIGHTING_ZELDA3D_ENV_RECORD_H

#ifdef __cplusplus
extern "C" {
#endif

/** One environment-light palette slot: the N64 `EnvLightSettings` colours plus the 3DS distances. */
typedef struct {
    unsigned char amb[3];
    signed char l0dir[3];
    unsigned char l0col[3];
    signed char l1dir[3];
    unsigned char l1col[3];
    unsigned char fogCol[3];
    unsigned short fogNear;
    float fogFar;
    float zFar;
} Zelda3dLightSlot;

/**
 * One scene's slots. `slots` is NULL when the scene has no recovered palette, so "no data" and "an
 * empty palette" stay distinguishable and a caller can never dereference a zero-length array.
 */
typedef struct {
    unsigned char numSlots;
    const Zelda3dLightSlot* slots;
} Zelda3dSceneLight;

#ifdef __cplusplus
}
#endif

#endif // ZELDA3D_SHARED_LIGHTING_ZELDA3D_ENV_RECORD_H
