// SoH3D — OoT3D Link (player) replacement POLICY. Owns the player draw, the equipment mesh-id mask,
// the per-bone retarget correction table + hand-weave state, the pose-freeze, linkpin, the cucco-grab
// repro driver, and all the `link*` REPL commands. The LOW-LEVEL CMB skeleton forward-kinematics
// retarget primitives (SoH3D_UpdateAnimN64*, SoH3D_PosedGroundOffset, ...) stay in soh3d_model.cpp;
// this file CALLS them. Split out of soh3d.c (pure refactor). C-ABI so soh3d.c can call in.
#ifndef SOH3D_LINK_H
#define SOH3D_LINK_H

#include "global.h"

#ifdef __cplusplus
extern "C" {
#endif

// Per-OoT3D-bone retarget correction (mirrors the typedef in soh3d_model.cpp; C ABI). mode: 0=rest
// (keep CMB rest), 1=replace (local rot := N64 rot), 2=left (C·R_n64), 3=right (R_n64·C). C is a
// row-major 3x3 constant rest-frame correction for bones whose OoT3D rest diverges from the N64
// limb's. Generated by tools/soh3d_link_retarget_derive.py -> soh3d_link_bonecorr.inc.
typedef struct {
    signed char limb;
    unsigned char mode; // 0 rest, 1 replace, 2 left C·R, 3 right R·C, 4 two-sided C·R·C2
    float C[9];
    float C2[9];
} SoH3dBoneCorr;

// Retarget the OoT3D skeleton from a live N64 pose with an explicit bone correspondence (NULL
// map = identity). Defined in soh3d_model.cpp.
void SoH3D_UpdateAnimN64Mapped(int modelId, const s16* jointRots, int rotCount, const signed char* boneToLimb,
                               int mapCount);
// As SoH3D_UpdateAnimN64Mapped but with a per-bone correction table (indexed by bone id). Defined
// in soh3d_model.cpp.
void SoH3D_UpdateAnimN64Corr(int modelId, const s16* jointRots, int rotCount, const SoH3dBoneCorr* corr,
                             int corrCount);

// OoT3D Link (player) replacement, called from Player_Draw (declared also in soh3d.h for the engine
// call site). Draws the OoT3D link body CMB at the player's transform; returns 1 if it drew.
int SoH3D_TryDrawPlayer(PlayState* play, Actor* actor);

// #6/#9 cucco-grab repro driver: extracted from SoH3D_WalkInject. Holds the asel-selected actor in
// front of Link + injects fresh A edges until grabbed. No-op unless `linkgrab` armed it.
void SoH3D_LinkWalkInject(PlayState* play);

// #8 hand-weave: pin Link's world pos + facing yaw each frame, so the side-profile view is identical
// across `linkcorr` tweaks. Extracted from SoH3D_ActorPostUpdate; called from that same call site.
void SoH3D_LinkApplyPin(PlayState* play, Actor* actor);

// Handle a `link*` REPL command. Returns 1 if `cmd` was a link command (and handled), 0 otherwise.
int SoH3D_LinkRepl(PlayState* play, const char* cmd, const char* line, const char* outPath);

#ifdef __cplusplus
}
#endif

#endif
