#!/usr/bin/env python3
"""cmb_to_c.py — convert an OoT3D CMB model into a self-contained N64/F3DEX2
display list + full-res RGBA32 texture, emitted as a C source + header that
Ship of Harkinian compiles directly.

This is SoH3D approach "A done right": rather than feeding the texture through
the modelled 4 KB TMEM, we emit manual load commands with the *real* pixel
width. libultraship's interpreter (GfxDpLoadBlock / ImportTextureRgba32) reads
the texture straight from the source pointer at full resolution — exactly the
path SoH's HD texture packs use — so there is no 4 KB limit. The actor's world
matrix is already on the RSP stack when the dlist runs (Gfx_DrawDListOpa), so
the mesh lands at the correct in-world transform for free.

Geometry is batched into <=10 triangles per gSPVertex load (<=30 of the 32 vtx
slots) so it works regardless of mesh size without vertex-cache bookkeeping.

Usage: cmb_to_c.py <model.cmb> <out_basename> [--tex N] [--scale F] [--no-flip-v]
Emits  <out_basename>.c and <out_basename>.h.
"""
import sys, os, struct, math
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from cmb import Cmb
import pica_texture

def clamp_s16(v):
    v = int(round(v))
    return -32768 if v < -32768 else 32767 if v > 32767 else v

def pack_n8(nx, ny, nz):
    """Normalize a normal and pack each component as an s8 byte (two's complement),
    the layout F3DEX2 reads from the Vtx color slot under G_LIGHTING."""
    l = math.sqrt(nx * nx + ny * ny + nz * nz) or 1.0
    def b(v):
        i = int(round(max(-1.0, min(1.0, v / l)) * 127.0))
        return i & 0xFF
    return b(nx), b(ny), b(nz)

def main():
    if len(sys.argv) < 3:
        print(__doc__); sys.exit(1)
    cmb_path, out_base = sys.argv[1], sys.argv[2]
    tex_index = 0
    scale = 1.0
    flip_v = True
    lit = False  # default unlit: full-bright texture (3DS look). --lit uses N64
                 # per-vertex lighting from CMB normals (bands on low-poly meshes
                 # in low-ambient scenes; kept for when smoother models warrant it).
    args = sys.argv[3:]
    i = 0
    while i < len(args):
        a = args[i]
        if a == "--tex": tex_index = int(args[i+1]); i += 2
        elif a == "--scale": scale = float(args[i+1]); i += 2
        elif a == "--no-flip-v": flip_v = False; i += 1
        elif a == "--lit": lit = True; i += 1
        else: print("unknown arg", a); sys.exit(1)

    c = Cmb(open(cmb_path, "rb").read())
    ident = os.path.basename(out_base).replace("-", "_")

    # --- texture: decode to RGBA32 at full resolution ---
    tex = c.textures[tex_index]
    tdata = c.data[c.texdata_ptr + tex.data_offset : c.texdata_ptr + tex.data_offset + tex.data_len]
    rgba = pica_texture.decode(tex.gl_format, tex.width, tex.height, tdata)
    assert len(rgba) == tex.width * tex.height * 4, \
        f"decoded {len(rgba)} bytes, expected {tex.width*tex.height*4}"
    TW, TH = tex.width, tex.height

    # --- geometry: collect triangles, build batches ---
    # Each entry: (s16 x,y,z, s16 s,t)  with white vertex color.
    tris = []  # list of [v0,v1,v2] where vN is a vtx tuple
    for sepd_i, mat_i, tri in c.triangles():
        face = []
        for idx, pos, nrm, uv in tri:
            x = clamp_s16(pos[0] * scale)
            y = clamp_s16(pos[1] * scale)
            z = clamp_s16(pos[2] * scale)
            u, v = uv[0], uv[1]
            if flip_v: v = 1.0 - v
            s = clamp_s16(u * TW * 32.0)
            t = clamp_s16(v * TH * 32.0)
            nx, ny, nz = pack_n8(nrm[0], nrm[1], nrm[2])
            face.append((x, y, z, s, t, nx, ny, nz))
        tris.append(face)

    BATCH = 10  # <=10 tris -> <=30 vtx slots (cache holds 32)
    batches = [tris[i:i+BATCH] for i in range(0, len(tris), BATCH)]

    masks = (TW.bit_length() - 1)
    maskt = (TH.bit_length() - 1)
    line_words = (TW * 4) >> 3  # 64-bit words per row, RGBA32

    h = []
    h.append(f"// Generated by tools/cmb_to_c.py from {os.path.basename(cmb_path)}")
    h.append(f"// model '{c.name}' v{c.version}: {len(tris)} tris, tex {tex.name} {TW}x{TH}")
    h.append("#ifndef SOH3D_%s_H" % ident.upper())
    h.append("#define SOH3D_%s_H" % ident.upper())
    h.append("#include <libultraship/libultra/gbi.h>")
    h.append(f"extern Gfx {ident}_dl[];")
    h.append("#endif")

    s = []
    s.append(f"// Generated by tools/cmb_to_c.py — do not edit by hand.")
    s.append(f'#include "{ident}.h"')
    s.append("")
    # texture (RGBA32)
    s.append(f"static const u8 {ident}_tex[{TW*TH*4}] __attribute__((aligned(8))) = {{")
    line = "    "
    for bi, byte in enumerate(rgba):
        line += "%d," % byte
        if (bi & 15) == 15:
            s.append(line); line = "    "
    if line.strip(): s.append(line)
    s.append("};")
    s.append("")
    # vertices: one flat array, batches index into contiguous ranges
    s.append(f"static const Vtx {ident}_vtx[] = {{")
    for b in batches:
        for face in b:
            for (x, y, z, sc, tc, nx, ny, nz) in face:
                # cn[4]: packed s8 normal for G_LIGHTING (--lit), else white color
                # (unlit -> shade = white -> texture shown at full brightness).
                cn = f"{nx},{ny},{nz},255" if lit else "255,255,255,255"
                s.append(f"    {{{{ {{{x},{y},{z}}}, 0, {{{sc},{tc}}}, {{{cn}}} }}}},")
    s.append("};")
    s.append("")
    # display list
    s.append(f"Gfx {ident}_dl[] = {{")
    s.append("    gsDPPipeSync(),")
    if not lit:
        # Unlit: drop scene lighting/fog so the white vertex color is the shade
        # (full-bright texture) instead of being read as a normal.
        s.append("    gsSPClearGeometryMode(G_LIGHTING | G_FOG),")
    s.append("    gsDPSetCombineMode(G_CC_MODULATERGBA, G_CC_MODULATERGBA),")
    s.append("    gsSPTexture(0xFFFF, 0xFFFF, 0, G_TX_RENDERTILE, G_ON),")
    s.append(f"    gsDPSetTextureImage(G_IM_FMT_RGBA, G_IM_SIZ_32b, {TW}, {ident}_tex),")
    s.append("    gsDPSetTile(G_IM_FMT_RGBA, G_IM_SIZ_32b, 0, 0, G_TX_LOADTILE, 0,")
    s.append("                G_TX_WRAP, 0, 0, G_TX_WRAP, 0, 0),")
    s.append(f"    gsDPLoadBlock(G_TX_LOADTILE, 0, 0, {TW*TH-1}, 0),")
    s.append(f"    gsDPSetTile(G_IM_FMT_RGBA, G_IM_SIZ_32b, {line_words}, 0, G_TX_RENDERTILE, 0,")
    s.append(f"                G_TX_WRAP, {maskt}, 0, G_TX_WRAP, {masks}, 0),")
    s.append(f"    gsDPSetTileSize(G_TX_RENDERTILE, 0, 0, {(TW-1)<<2}, {(TH-1)<<2}),")
    vbase = 0
    for b in batches:
        nv = len(b) * 3
        s.append(f"    gsSPVertex(&{ident}_vtx[{vbase}], {nv}, 0),")
        for ti in range(len(b)):
            a = ti*3
            s.append(f"    gsSP1Triangle({a}, {a+1}, {a+2}, 0),")
        vbase += nv
    s.append("    gsSPEndDisplayList(),")
    s.append("};")
    s.append("")

    with open(out_base + ".h", "w") as f: f.write("\n".join(h) + "\n")
    with open(out_base + ".c", "w") as f: f.write("\n".join(s) + "\n")
    print(f"wrote {out_base}.c / .h: {len(tris)} tris, {len(batches)} batches, tex {TW}x{TH} RGBA32")

if __name__ == "__main__":
    main()
