#!/usr/bin/env python3
"""Generate the committed SoH-sceneNum -> OoT3D-scene-folder-name table.

`play->sceneNum` is the SceneID enum value, and SceneID is generated from
soh/include/tables/scene_table.h via DEFINE_SCENE in order, so the enum value equals
the table row index. We emit a positional `const char*` array indexed by sceneNum.

OoT3D mostly reuses the N64 internal scene segment names (lower-cased). A handful were
renamed (dungeon bosses, houses, shops, market entrances); those get explicit overrides
below. Scenes with no OoT3D equivalent (test/beta) map to NULL -> the engine falls back
to the N64 room. Output is names only (no ROM assets) -> safe to commit.

Run: ZELDA3D_OOT3D_ROM=<path.3ds> python3 tools/gen_scene_names.py
"""
import os, re, sys
sys.path.insert(0, os.path.dirname(__file__))
from ctr_romfs import CtrRom

REPO = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
SCENE_TABLE = os.path.join(REPO, "Shipwright/soh/include/tables/scene_table.h")
# The table the BUILD includes (scene_replacement.c does `#include "../tables/zelda3d_scene_names.inc"`).
# This previously wrote to Shipwright/soh/src/zelda3d/zelda3d_scene_names.inc -- a path nothing
# includes -- so regenerating produced a second, untracked copy of the same data while the
# tracked table kept its old contents. The two had already drifted in their header count
# (102/111 generated vs 101/110 written) while every NAME still matched, which is the worst
# kind of divergence: it looks fine until the copy someone edits is not the copy that builds.
OUT = os.path.join(REPO, "Shipwright/soh/src/zelda3d/tables/zelda3d_scene_names.inc")

# SoH scene segment name (sans `_scene`) -> OoT3D folder name, for the renamed scenes.
OVERRIDES = {
    "moribossroom": "moriboss",
    "FIRE_bs": "fire_bs",
    "MIZUsin_bs": "mizusin_boss",
    "jyasinboss": "jyasinzou_boss",
    "HAKAdan_bs": "hakadan_boss",
    "HAKAdanCH": "hakadan_ch",
    "entra": "entra_day",
    "entra_n": "entra_night",
    "enrui": "entra_ruins",
    "kokiri_home": "k_home",
    "kokiri_home3": "k_home3",
    "kokiri_home4": "k_home4",
    "kokiri_home5": "k_home5",
    "kakariko3": "kakariko_home3",
    "shop1": "shop",
    "kokiri_shop": "shop",  # OoT3D reuses the Bazaar geometry for the Kokiri shop
    "golon": "shop_golon",
    "drag": "shop_drag",
    "alley_shop": "shop_alley",
    "night_shop": "shop_night",
    "face_shop": "shop_face",
    "link_home": "link",
    "impa": "kakariko_impa",
    "malon_stable": "stable",
}


def main():
    rom = CtrRom(os.environ["ZELDA3D_OOT3D_ROM"])
    folders = set()
    for f in rom.iter_files():
        p = f if isinstance(f, str) else getattr(f, "path", str(f))
        m = re.match(r"/scene/([a-zA-Z0-9_]+)_info\.zsi$", p)
        if m:
            folders.add(m.group(1))
    # case-insensitive lookup -> actual folder casing
    ci = {n.lower(): n for n in folders}

    rows = []  # (soh_name, enum, oot3d_name_or_None)
    table = Path(SCENE_TABLE).read_text(encoding="utf-8")
    for line in table.splitlines():
        m = re.search(r"DEFINE_SCENE\(\s*([A-Za-z0-9_]+)_scene\s*,\s*[A-Za-z0-9_]+\s*,\s*(SCENE_[A-Z0-9_]+)", line)
        if not m:
            continue
        soh, enum = m.group(1), m.group(2)
        name = None
        if soh in OVERRIDES:
            name = OVERRIDES[soh]
            if name not in folders:
                print(f"WARN override {soh}->{name} not in ROM", file=sys.stderr)
                name = None
        elif soh.lower() in ci:
            name = ci[soh.lower()]
        rows.append((soh, enum, name))

    mapped = sum(1 for _, _, n in rows if n)
    # Preserved prose that lives INSIDE the generated table, keyed by the sceneNum it documents.
    # Comments in a generated file are normally a smell, but this one records why sceneNum 0x6E maps
    # to spot99 at all (its N64 actor/object/collision data is aliased from spot00, byte-identical per
    # title_scene_spot99.md §3/§4, while the OoT3D render/collision layer loads spot99's own ZSI) --
    # knowledge that is not derivable from the table and would otherwise be lost on the next
    # regeneration. It is restored by sceneNum, not by position, so adding a row cannot shift it onto
    # the wrong scene.
    PRESERVED = {
        0x6E: (
            "    // SoH3D title scene: OoT3D's dedicated title-demo scene (3DS scene index 0x6b). Its N64\n"
            "    // actor/object/collision data is aliased from spot00 (byte-identical per title_scene_spot99.md\n"
            "    // §3/§4), but the OoT3D render/collision layer loads spot99's own ZSI from here."
        )
    }

    with open(OUT, "w") as o:
        o.write("// GENERATED by tools/gen_scene_names.py — do not edit by hand.\n")
        o.write("// SoH sceneNum (SceneID enum, == scene_table.h row index) -> OoT3D scene\n")
        o.write("// folder name (for /scene/<name>_<R>_info.zsi). NULL = no OoT3D scene\n")
        o.write("// (fall back to the N64 room). Names only; no ROM-derived assets.\n")
        o.write(f"// {mapped}/{len(rows)} scenes mapped.\n")
        o.write("static const char* const kZelda3dSceneNames[] = {\n")
        for i, (soh, enum, name) in enumerate(rows):
            val = f"\"{name}\"" if name else "NULL"
            if i in PRESERVED:
                o.write(PRESERVED[i] + "\n")
            o.write(f"    /* 0x{i:02X} {enum:<40} ({soh}) */ {val},\n")
        o.write("};\n")
    print(f"wrote {OUT}: {mapped}/{len(rows)} scenes mapped")


if __name__ == "__main__":
    main()
