#!/usr/bin/env python3
"""Generate the PLAYER (Link) N64-anim -> OoT3D-CSAB table: soh3d_player_animmap.inc.

Link is special-cased (NOT the SOH3D_AUTO path): SoH3D_TryDrawPlayer reads the live
Player.skelAnime.animation (a const char* OTR string, basename gPlayerAnim_link_*) and plays
the OoT3D *_new link rig's OWN matching CSAB, phase-locked. See memory soh3d-link-player-path.

The N64 decomp anim names map to the 3DS CSAB names by a small set of category-prefix + token
rewrites (e.g. normal_->nml_, fighter_->ft_, demo_->dm_, finsh->fin, power->pow). This generator
applies those rules to every gPlayerAnim_link_* symbol in the SoH source and EMITS ONLY the pairs
whose resolved CSAB actually exists in BOTH the boy and child *_new zars (so one basename table is
correct for either age). An N64 anim with no resolvable CSAB is omitted -> the runtime resolver
falls back to SOH3D_LINK_IDLE_CSAB (so Link reads as standing, never frozen in bind pose).

The REWRITE RULES are the real knowledge here; the table is just their verified projection. To
extend coverage, add a rule below and rerun. Validation against the live zar means a wrong rule
can only ever drop an entry, never emit a bad one.

Run:  . ./.env && python3 tools/gen_player_animmap.py
Needs SOH3D_3DS_ROM (the decrypted OoT3D ROM) for the link zars.
"""
import os
import re
import subprocess
import sys

sys.path.insert(0, os.path.join(os.path.dirname(os.path.abspath(__file__))))
from ctr_romfs import CtrRom  # noqa: E402
import zar  # noqa: E402

REPO = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
OUT = os.path.join(REPO, "Shipwright/soh/src/soh3d/soh3d_player_animmap.inc")
SRC = os.path.join(REPO, "Shipwright/soh/src")

PREFIX = "gPlayerAnim_link_"

# Leading category token: N64 decomp name -> OoT3D CSAB prefix.
CATEGORY = [
    ("normal_", "nml_"),
    ("fighter_", "ft_"),
    ("demo_", "dm_"),
    ("anchor_", "ac_"),
    ("bottle_", "bt_"),
    ("hammer_", "hm_"),
    ("magic_", "mg_"),
    ("swimer_", "sw_"),
    # bow_, boom_, fishing_, hook_, uma_, silver_, derth_, last_ keep their prefix.
]

# Substring rewrites applied AFTER the category substitution (Grezzo's naming tweaks).
SUBS = [
    ("finsh", "fin"),               # *_kiru_finsh_* -> *_kiru_fin_*
    ("normal_kiru", "nml_kiru"),    # fighter_normal_kiru -> ft_nml_kiru
    ("Lnormal", "Lnml"),            # fighter_Lnormal_kiru -> ft_Lnml_kiru
    ("power", "pow"),               # *_power_*/_Lpower_* -> *_pow_*/_Lpow_*
    ("pierce_kiru", "pierce"),      # fighter_pierce_kiru -> ft_pierce
    ("down_slope_slip", "down_slip"),
    ("up_slope_slip", "up_slip"),
    ("normal2", "nml2"),            # normal_normal2fighter -> nml_nml2fighter
    ("free2fighter_free", "free2ft_free"),
    ("drink_demo", "drink_dm"),     # bottle_drink_demo_* -> bt_drink_dm_*
    ("doorA_link", "doorA_lk"),     # demo_doorA_link -> dm_doorA_lk
    ("doorB_link", "doorB_lk"),
    ("kakeyori", "runup"),          # demo_kakeyori_* -> dm_runup_*
]


def csab_basenames(rom, zarpath):
    z = zar.Zar(rom.read(rom.get(zarpath)))
    return set(os.path.basename(f.name)[:-5] for f in z.files if f.name.endswith(".csab"))


def resolve(n64name):
    s = n64name[len(PREFIX):]
    for k, v in CATEGORY:
        if s.startswith(k):
            s = v + s[len(k):]
            break
    for a, b in SUBS:
        s = s.replace(a, b)
    return s


def main():
    rom = CtrRom(os.environ["SOH3D_3DS_ROM"])
    boy = csab_basenames(rom, "/actor/zelda_link_boy_new.zar")
    child = csab_basenames(rom, "/actor/zelda_link_child_new.zar")
    shared = boy & child  # one basename table must resolve for either age

    out = subprocess.check_output(
        ["grep", "-rho", "gPlayerAnim_link_[a-zA-Z0-9_]*", SRC]
    ).decode().split()
    names = sorted(set(out))

    rows = []
    dropped = []
    for n in names:
        if not re.fullmatch(r"gPlayerAnim_link_[A-Za-z0-9_]+", n):
            continue
        c = resolve(n)
        if c in shared:
            rows.append((n, c))
        else:
            dropped.append((n, c))

    lines = []
    lines.append("// GENERATED by tools/gen_player_animmap.py — do not edit by hand.")
    lines.append("// PLAYER (Link) N64-anim -> OoT3D-link-CSAB map. Key = the live")
    lines.append("// Player.skelAnime.animation basename (gPlayerAnim_link_*); value = the CSAB base")
    lines.append("// played on the *_new link rig (resolved to boy/anim or child/anim by age). Only")
    lines.append("// pairs whose CSAB exists in BOTH age zars are emitted; an unlisted anim falls")
    lines.append("// back to SOH3D_LINK_IDLE_CSAB at runtime. Edit the rewrite rules in the generator,")
    lines.append("// not this file. See memory soh3d-link-player-path.")
    lines.append("static const SoH3dPlayerAnimMap kPlayerAnimMap[] = {")
    for n, c in rows:
        lines.append('    { "%s", "%s" },' % (n, c))
    lines.append("};")
    lines.append("")

    with open(OUT, "w") as f:
        f.write("\n".join(lines))

    print("wrote %s: %d entries (%d N64 anims, %d unmapped -> idle fallback)"
          % (os.path.relpath(OUT, REPO), len(rows), len(names), len(dropped)))


if __name__ == "__main__":
    main()
