#!/usr/bin/env python3
"""Generate the committed OoT3D per-scene lighting palette table for the #111
vertex-lighting port.

Parses each OoT3D scene-header ZSI (`/scene/<name>_info.zsi`) env-settings command
(0x0F) using the native-3DS 28-byte layout. The byte offsets below were re-derived 2026-06-24
by matching the parsed bytes against the LIVE Azahar oracle runtime EnvLightSettings
(oot3d-decomp/docs/ram_map.md "ENVIRONMENT LIGHTING"); the offsets in scene_lighting.md
were WRONG for the light colors (had l0col @ +0x06 = a constant field). VALIDATED layout:

    +0x00 u8[3] ambient   +0x04 u8[3] light0Color   +0x07 s8[3] light0Dir
    +0x0a u8[3] light1Color  +0x0d s8[3] light1Dir   +0x10 f32 fogEnd  +0x14 f32 drawDist

(ambient @ +0x00, l0col @ +0x04, l1col @ +0x0a confirmed against runtime noon/night/dusk
slots for spot04: noon l0col=(255,255,219), night=(63,63,99), dusk=(239,140,61).) The
day/night brightness is carried by **light0Color** (the sun), NOT ambient (~constant).

Entry 0 is a metadata blob; the RUNTIME drops it, so runtime slot i = ZSI entry (i+1).
We emit ALL entries (entry 0 included) so the runtime can apply slot bias +1 to align the
N64 z_kankyo schedule index with the matching OoT3D entry.

Output: a positional array `kZelda3dSceneLighting[]` indexed by SoH sceneNum (same order as
kZelda3dSceneNames / scene_table.h), each row = the scene's slot palette. Values only (tiny
tuning ints) — safe to commit, like zelda3d_scene_names.inc and n64_scene_lighting.json.

Run: ZELDA3D_3DS_ROM=<path.3ds> python3 tools/gen_oot3d_scene_lighting.py
"""
import os, re, sys, struct
sys.path.insert(0, os.path.dirname(__file__))
from ctr_romfs import CtrRom
import gen_scene_names as gsn  # reuse OVERRIDES + SCENE_TABLE row derivation

REPO = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
OUT = os.path.join(REPO, "Shipwright/soh/src/zelda3d/zelda3d_scene_lighting.inc")
STRIDE = 0x1C


def parse_env(d):
    """Return list of slots (skipping entry 0 metadata); each slot is a dict of int lists."""
    off = 16
    env = None
    while off + 8 <= len(d):
        cmd1 = struct.unpack_from(">I", d, off)[0]
        cmd2 = struct.unpack_from("<I", d, off + 4)[0]
        ctype = (cmd1 >> 24) & 0xFF
        count = (cmd1 >> 16) & 0xFF
        if ctype == 0x0F:
            env = (count, cmd2)
        off += 8
        if ctype == 0x14:
            break
    if not env:
        return []
    count, addr = env
    base = addr if (16 <= addr and addr + count * STRIDE <= len(d)) else (addr & 0xFFFFFF)
    if base + count * STRIDE > len(d):
        return []
    slots = []
    # Emit ALL entries including entry 0. The decomp doc calls entry 0 a metadata blob,
    # but the runtime slot↔N64-slot alignment (entry-i vs off-by-one) is UNRESOLVED offline
    # (see docs/oot3d_world_lighting_re.md "#111") — keep entry 0 so the live-verification
    # session has the full palette and can pick the alignment empirically.
    for i in range(0, count):
        o = base + i * STRIDE
        def u(off, n):  # unsigned bytes
            return list(d[o + off:o + off + n])
        def s(off, n):  # signed bytes
            return [b - 256 if b >= 128 else b for b in d[o + off:o + off + n]]
        slots.append({
            "amb": u(0x00, 3), "l0col": u(0x04, 3), "l0dir": s(0x07, 3),
            "l1col": u(0x0a, 3), "l1dir": s(0x0d, 3),
        })
    return slots


def main():
    rom = CtrRom(os.environ["ZELDA3D_3DS_ROM"])
    # name -> file path, case-insensitive
    name_path = {}
    for f in rom.iter_files():
        p = f if isinstance(f, str) else getattr(f, "path", str(f))
        m = re.match(r"/scene/([a-zA-Z0-9_]+)_info\.zsi$", p)
        if m:
            name_path[m.group(1)] = p
    ci = {n.lower(): n for n in name_path}

    # Reproduce gen_scene_names row order + name resolution.
    rows = []  # (soh, enum, oot3d_name|None)
    for line in open(gsn.SCENE_TABLE):
        m = re.search(r"DEFINE_SCENE\(\s*([A-Za-z0-9_]+)_scene\s*,\s*[A-Za-z0-9_]+\s*,\s*(SCENE_[A-Z0-9_]+)", line)
        if not m:
            continue
        soh, enum = m.group(1), m.group(2)
        name = None
        if soh in gsn.OVERRIDES:
            cand = gsn.OVERRIDES[soh]
            if cand in name_path:
                name = cand
        elif soh.lower() in ci:
            name = ci[soh.lower()]
        rows.append((soh, enum, name))

    # Parse each distinct scene's slots once.
    parsed = {}
    for _, _, name in rows:
        if name and name not in parsed:
            parsed[name] = parse_env(rom.read(rom.get(name_path[name])))

    mapped = sum(1 for _, _, n in rows if n and parsed.get(n))
    with open(OUT, "w") as o:
        o.write("// GENERATED by tools/gen_oot3d_scene_lighting.py — do not edit by hand.\n")
        o.write("// OoT3D per-scene env-light palette for the #111 vertex-lighting port.\n")
        o.write("// Native-3DS ZSI cmd 0x0F, 28-byte layout (entry 0 = metadata, skipped).\n")
        o.write("// Slot i aligns with N64 light-settings slot i, so the N64 z_kankyo time\n")
        o.write("// schedule selects the matching OoT3D slot. See docs/oot3d_world_lighting_re.md.\n")
        o.write(f"// {mapped}/{len(rows)} scenes have a palette.\n\n")
        o.write("typedef struct {\n")
        o.write("    unsigned char amb[3]; signed char l0dir[3]; unsigned char l0col[3];\n")
        o.write("    signed char l1dir[3]; unsigned char l1col[3];\n")
        o.write("} Zelda3dLightSlot;\n")
        o.write("typedef struct { unsigned char numSlots; const Zelda3dLightSlot* slots; } Zelda3dSceneLight;\n\n")

        emitted = {}
        for name in sorted(parsed):
            slots = parsed[name]
            if not slots:
                continue
            sym = "kSlots_" + re.sub(r"[^A-Za-z0-9_]", "_", name)
            emitted[name] = sym
            o.write(f"static const Zelda3dLightSlot {sym}[] = {{ // {name}\n")
            for s in slots:
                o.write("    {{%3d,%3d,%3d},{%4d,%4d,%4d},{%3d,%3d,%3d},{%4d,%4d,%4d},{%3d,%3d,%3d}},\n" % (
                    *s["amb"], *s["l0dir"], *s["l0col"], *s["l1dir"], *s["l1col"]))
            o.write("};\n")
        o.write("\nstatic const Zelda3dSceneLight kZelda3dSceneLighting[] = {\n")
        for i, (soh, enum, name) in enumerate(rows):
            if name and parsed.get(name):
                o.write(f"    /* 0x{i:02X} {enum:<36} */ {{ {len(parsed[name])}, {emitted[name]} }},\n")
            else:
                o.write(f"    /* 0x{i:02X} {enum:<36} */ {{ 0, 0 }},\n")
        o.write("};\n")
    print(f"wrote {OUT}: {mapped}/{len(rows)} scenes have a palette")


if __name__ == "__main__":
    main()
