#!/usr/bin/env python3
"""oracle_link_animid.py — capture OoT3D Link's LIVE selected animation (animId -> name) per frame.

The SELECTION half of the Link parity sweep (#117): which CSAB does OoT3D PLAY, frame by frame?
Pairs with the Zelda3D side (REPL `skindump`, which tags the resolved CSAB name) and the geometry
half (oracle_link_pose.py / parity_pose_diff.py). The slide bug (#117) is a SELECTION divergence:
Zelda3D sometimes resolves a WAIT anim while OoT3D plays a locomotion anim.

How animId resolves to a name (RE'd 2026-06-25, FUN_0034807c; oot3d-decomp docs/player_anim_states.md):
    skelAnime = PLAYER + 0x254
    curAnimId = *(skelAnime + 0x30)              # the selected animation id
    animSet   = *(skelAnime + 0x04)              # PLAYER+0x258
    csabArr   = *(animSet + 0x50)                # array of csab descriptors (ZAR file order)
    csabData  = *(csabArr[curAnimId] + 0)        # raw 'csab' resource (for live duration check)
animId is a file-order index into /actor/zelda_link_boy_new.zar (582 CSABs); the name table is
oot3d-decomp/tools/skeldata/player_animid_names.json (generated by gen_player_animid_table.py).

Usage:
  tools/oracle_link_animid.py --frames 120 --hold-circle 0,100          # drive a forward run
  tools/oracle_link_animid.py --frames 80  --out scratch/parity/oracle_sel.csv
  tools/oracle_link_animid.py --watch                                   # print on every change
Options mirror oracle_link_pose.py (--hold-circle CX,CY, --hold-buttons, --hz, --timeout).
"""
import argparse, json, os, struct, sys, time

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import azahar_rpc as A

OOT3D_TID = 0x0004000000033500
GPLAYSTATE = 0x0050AF34
SKELANIME_OFF = 0x254
ANIMID_OFF = 0x30        # skelAnime -> curAnimId
ANIMSET_OFF = 0x04       # skelAnime -> anim-set handle
CSABARR_OFF = 0x50       # animSet -> csab descriptor array
MORPH_OFF = 0x34         # skelAnime -> morphWeight
CURFRAME_OFF = 0x3c      # skelAnime -> curFrame
PLAYSPEED_OFF = 0x40     # skelAnime -> playSpeed

_TABLE = os.path.join(os.path.dirname(__file__), "..", "..", "oot3d-decomp",
                      "tools", "skeldata", "player_animid_names.json")


def load_table():
    t = json.load(open(os.path.abspath(_TABLE)))
    return t["names"], t["byId"]


def select_oot3d(rpc):
    for pid, tid, _ in rpc.processes():
        if tid == OOT3D_TID:
            rpc.select(pid)
            return pid
    return None


def link_actor(rpc):
    ps = rpc.read32(GPLAYSTATE)
    if not ps:
        sys.exit("oracle_link_animid: no PlayState (title screen?) — boot into a scene first")
    return rpc.read32(ps + 0x208C + 0x0C + 2 * 8 + 4)


def live_csab_duration(rpc, animSet, animId):
    """Live CSAB frameCount for animId (sanity-checks the static table against RAM)."""
    arr = rpc.read32(animSet + CSABARR_OFF)
    if not arr:
        return None
    desc = rpc.read32(arr + animId * 4)
    if not desc:
        return None
    data = rpc.read32(desc + 0)
    if not data:
        return None
    hdr = rpc.read(data, 0x40)
    if hdr[:4] != b"csab":
        return None
    return struct.unpack_from("<I", hdr, 0x28)[0] + 1


def sample(rpc, actor, names):
    skel = actor + SKELANIME_OFF
    animId = rpc.read32(skel + ANIMID_OFF)
    animSet = rpc.read32(skel + ANIMSET_OFF)
    name = names[animId] if 0 <= animId < len(names) else f"<id {animId}>"
    mw = struct.unpack("<f", rpc.read(skel + MORPH_OFF, 4))[0]
    cf = struct.unpack("<f", rpc.read(skel + CURFRAME_OFF, 4))[0]
    ps = struct.unpack("<f", rpc.read(skel + PLAYSPEED_OFF, 4))[0]
    return {"animId": animId, "name": name, "morphWeight": round(mw, 4),
            "curFrame": round(cf, 3), "playSpeed": round(ps, 3), "animSet": animSet}


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--frames", type=int, default=120)
    ap.add_argument("--hz", type=float, default=30.0)
    ap.add_argument("--hold-circle", default=None, help="CX,CY in -100..100")
    ap.add_argument("--hold-buttons", default="", help="space-separated button names")
    ap.add_argument("--out", default=None)
    ap.add_argument("--watch", action="store_true", help="print only on animId change, until Ctrl-C")
    ap.add_argument("--timeout", type=float, default=20.0)
    args = ap.parse_args()

    rpc = A.Rpc()
    if select_oot3d(rpc) is None:
        sys.exit("oracle_link_animid: OoT3D process not found in Azahar")
    names, by_id = load_table()
    actor = link_actor(rpc)
    if not actor:
        sys.exit("oracle_link_animid: no PLAYER actor (not in gameplay yet)")

    circle = None
    if args.hold_circle:
        cx, cy = (int(x) for x in args.hold_circle.split(","))
        circle = (cx, cy)
    btn_mask = A.buttons_mask(args.hold_buttons) if args.hold_buttons else 0

    def drive():
        if circle is not None or btn_mask:
            rpc.set_input(btn_mask, circle)

    rows, last = [], None
    period = 1.0 / args.hz
    n = 0
    try:
        while True:
            drive()
            s = sample(rpc, actor, names)
            key = s["animId"]
            if args.watch:
                if key != last:
                    dur = live_csab_duration(rpc, s["animSet"], s["animId"])
                    print(f"animId {s['animId']:#04x} {s['name']:<22} "
                          f"frame={s['curFrame']:.1f} morph={s['morphWeight']:.2f} "
                          f"spd={s['playSpeed']:.2f} liveDur={dur}")
                    last = key
            else:
                rows.append(s)
                n += 1
                if n >= args.frames:
                    break
            time.sleep(period)
    except KeyboardInterrupt:
        pass

    if rows and not args.watch:
        # collapse to runs of constant animId for a readable selection timeline
        timeline, prev = [], None
        for i, s in enumerate(rows):
            if s["animId"] != prev:
                timeline.append({"frame_i": i, **s})
                prev = s["animId"]
        print(f"# {len(rows)} samples, {len(timeline)} selection changes")
        for t in timeline:
            print(f"  [{t['frame_i']:>3}] animId {t['animId']:#04x} {t['name']:<22} "
                  f"morph={t['morphWeight']:.2f} spd={t['playSpeed']:.2f}")
        if args.out:
            os.makedirs(os.path.dirname(os.path.abspath(args.out)), exist_ok=True)
            json.dump({"samples": rows, "timeline": timeline}, open(args.out, "w"), indent=0)
            print(f"# wrote {args.out}")


if __name__ == "__main__":
    main()
