#!/usr/bin/env bash
# Rasterize the keyboard-key glyph SVGs (B/C-Left/C-Down/C-Right) to PNGs and embed them as a
# single C header the HUD loads at runtime (stbi_load_from_memory -> persistent RGBA32). Run after
# editing any assets/soh3d/key_<slot>.svg. Mirror of tools/soh3d_gen_xbox_glyphs.sh.
#   tools/soh3d_gen_kbd_glyphs.sh
# Requires ImageMagick (magick/convert) with the librsvg delegate.
set -euo pipefail
REPO="$(cd "$(dirname "$0")/.." && pwd)"
ASSETS="$REPO/Shipwright/soh/assets/soh3d"
OUTDIR="$REPO/scratch/svg"; mkdir -p "$OUTDIR"
HDR="$REPO/Shipwright/soh/src/soh3d/kbd_glyphs_png.h"

RASTER=(magick); command -v magick >/dev/null 2>&1 || RASTER=(convert)

{
  echo "// GENERATED by tools/soh3d_gen_kbd_glyphs.sh from assets/soh3d/key_{b,cleft,cdown,cright}.svg — do not edit."
  echo "// Raw PNG bytes of the keyboard-key HUD glyphs; decoded at runtime via stbi_load_from_memory."
  echo "#pragma once"
} > "$HDR"

for SLOT in b cleft cdown cright; do
  SVG="$ASSETS/key_$SLOT.svg"
  PNG="$OUTDIR/key_$SLOT.png"
  "${RASTER[@]}" -background none "$SVG" -resize 64x64\! "$PNG"
  # Constant name: kKbdGlyph_B, kKbdGlyph_Cleft, etc.
  U="$(echo "${SLOT:0:1}" | tr 'a-z' 'A-Z')${SLOT:1}"
  {
    printf 'static const unsigned char kKbdGlyph_%sPng[] = {\n' "$U"
    od -An -v -tu1 "$PNG" | tr -s ' ' | sed 's/^ //; s/ /,/g; s/$/,/'
    printf '};\n'
    printf 'static const unsigned int kKbdGlyph_%sPngLen = sizeof(kKbdGlyph_%sPng);\n' "$U" "$U"
  } >> "$HDR"
  echo "rasterized $SVG -> $PNG ($(wc -c < "$PNG") bytes)"
done

echo "wrote $HDR"
