// MM3D per-scene lighting accessor. See mm3d_scene_lighting.h for why this is a data substitution
// into MM's own list rather than a second implementation of MM's blend, and why the stride is 0x16.

#include "mm3d_scene_lighting.h"

// Generated by tools/gen_mm3d_scene_lighting.py. Two tables with different jobs:
//   kMm3dEnvList     -- 0x16-stride N64-shaped records, for the lightSettingsList substitution
//   kMm3dSceneLighting -- the 0x20 records, whose f32 distances drive the PICA fog window
#include "mm3d_scene_lighting.inc"

/// Scene-table size, from the generated index itself rather than a duplicated constant: the two must
/// not be able to disagree, and a second literal is exactly how they eventually would.
#define MM3D_SCENE_TABLE_SIZE ((s16)(sizeof(kMm3dEnvList) / sizeof(kMm3dEnvList[0])))

static bool Mm3d_SceneInRange(s16 sceneNum) {
    return sceneNum >= 0 && sceneNum < MM3D_SCENE_TABLE_SIZE;
}

bool Mm3d_HasScenePalette(s16 sceneNum) {
    return Mm3d_SceneInRange(sceneNum) && kMm3dEnvList[sceneNum].numSlots != 0;
}

const Mm3dEnvLightSettings* Mm3d_SceneEnvList(s16 sceneNum, u8* outCount) {
    if (outCount != NULL) {
        *outCount = 0;
    }
    if (!Mm3d_HasScenePalette(sceneNum)) {
        return NULL;
    }
    if (outCount != NULL) {
        *outCount = kMm3dEnvList[sceneNum].numSlots;
    }
    return kMm3dEnvList[sceneNum].slots;
}

void Mm3d_ScenePaletteCoverage(u16* outScenes, u16* outSlots, u16* outClampedSlots) {
    u16 scenes = 0;
    u16 slots = 0;
    for (s16 i = 0; i < MM3D_SCENE_TABLE_SIZE; i++) {
        if (kMm3dEnvList[i].numSlots == 0) {
            continue;
        }
        scenes++;
        slots += kMm3dEnvList[i].numSlots;
    }
    if (outScenes != NULL) {
        *outScenes = scenes;
    }
    if (outSlots != NULL) {
        *outSlots = slots;
    }
    if (outClampedSlots != NULL) {
        // Reported from the generator, not recomputed: a clamped slot lands on S16_MAX, which is
        // indistinguishable from a legitimately huge zFar, so no consumer could detect it by
        // inspection. This keeps the loss visible without every reader having to diff the ROM.
        *outClampedSlots = MM3D_CLAMPED_ZFAR_SLOTS;
    }
}
