// MM3D's per-scene lighting, installed into MM's OWN light-settings list. Game-agnostic interface,
// MM-specific data.
//
// WHY THIS IS A DATA SUBSTITUTION AND NOT A REIMPLEMENTATION OF MM'S BLEND. MM's N64 code already
// computes the entire environment blend -- the time LERP, the config LERP, and the additive
// `adjLightSettings` term -- from ONE list pointer, `play->envCtx.lightSettingsList`, set in exactly
// one place (`z_scene.c`, `Scene_CommandEnvLightSettings`). The additive term is produced by
// `func_800F6CEC(play, index, &spA4[k], lightSettingsList)`, which takes the LIST AS A PARAMETER, so it
// derives from whatever list is installed. Installing the 3DS records therefore makes MM's own blend
// operate on 3DS data, and nothing about the blend has to be re-derived or kept in sync. That is why
// this module holds no blend arithmetic at all: a second implementation of MM's blend would be a
// divergent copy of game logic that already works.
//
// THE STRIDE. `EnvLightSettings` is 0x16 bytes (`2ship/include/z64environment.h:214`) and MM indexes
// `lightSettingsList[i]`, so it steps by 0x16. The 3DS record is 0x20. Substituting the 0x20 table
// directly would walk it in 0x16 steps: slot 0 would read correctly and EVERY LATER SLOT would read
// the wrong bytes -- a plausible frame rather than a crash. So `tools/gen_mm3d_scene_lighting.py`
// projects each record to the 0x16 N64 shape, and this module installs THAT. The PICA fog window needs
// the 3DS-only f32 distances, which do not exist in the N64 struct, so they stay in the 0x20
// `kMm3dSceneLighting` table and are read separately.
//
// This module is deliberately a leaf: it exposes one predicate, one accessor, and nothing else. It
// does not know about rendering, the renderer, or PICA.
#ifndef MM3D3D_SCENE_LIGHTING_H
#define MM3D3D_SCENE_LIGHTING_H

#include "ultra64.h"

// The 0x20 records, emitted alongside the 0x16 projection by the same generator, use the SHARED
// record type -- both games fill one struct, and the OoT3D table uses the same one. Including it here
// rather than redeclaring the fields is the point of having moved it to zelda3d_shared.
#include "lighting/zelda3d_env_record.h"

#ifdef __cplusplus
extern "C" {
#endif

/// One scene's N64-shaped light settings, as generated by tools/gen_mm3d_scene_lighting.py.
typedef struct {
    u8 ambientColor[3];
    s8 light1Dir[3];
    u8 light1Color[3];
    s8 light2Dir[3];
    u8 light2Color[3];
    u8 fogColor[3];
    s16 blendRateAndFogNear;
    s16 zFar;
} Mm3dEnvLightSettings; // size = 0x16, must equal sizeof(EnvLightSettings)

typedef struct {
    u8 numSlots;
    const Mm3dEnvLightSettings* slots;
} Mm3dEnvList;

/**
 * Does MM3D have a recovered palette for `sceneNum`?
 *
 * A false result means the scene falls back to the N64 light settings, which is the correct
 * behaviour rather than a failure: 11 of MM's 113 scene-table entries have no recovered palette, and
 * the N64 data is the right answer for those until it is recovered.
 */
bool Mm3d_HasScenePalette(s16 sceneNum);

/**
 * The N64-shaped list for `sceneNum`, or NULL when the scene has no recovered palette.
 *
 * Callers must substitute this as `play->envCtx.lightSettingsList` INSTEAD of the N64 pointer -- never
 * alongside it. It is `const` because the blend only reads it, and the additive term is derived from
 * the list rather than written to it.
 */
const Mm3dEnvLightSettings* Mm3d_SceneEnvList(s16 sceneNum, u8* outCount);

/// How many scenes have a recovered palette, and how many slots needed an s16 zFar clamp. Diagnostics.
void Mm3d_ScenePaletteCoverage(u16* outScenes, u16* outSlots, u16* outClampedSlots);

#ifdef __cplusplus
}
#endif

#endif // MM3D3D_SCENE_LIGHTING_H
